[paths]
"@service/*" = "src/api/service/*"
"@controller/*" = "src/api/controller/*"
"@repository/*" = "src/api/repository/*"
"@schema/*" = "src/api/schema/*"

"@docs/*" = "src/docs/*"
"@lib/*" = "src/lib/*"
"@util/*" = "src/util/*"
"@config/*" = "src/config/*"
"@error/*" = "src/error/*"
"@middleware/*" = "src/middleware/*"
"@generated/*" = "src/generated/*"
"@script/*" = "scr/script/*"