[paths]
"@api/*" = "src/api/*"

"@docs/*" = "src/docs/*"
"@lib/*" = "src/lib/*"
"@util/*" = "src/util/*"
"@config/*" = "src/config/*"
"@error/*" = "src/error/*"
"@middleware/*" = "src/middleware/*"
"@generated/*" = "src/generated/*"
"@script/*" = "scr/script/*"